python: can't open file '/script_pose_logfile.py': [Errno 2] No such file or directory
